export const UPDATE_FILTER = "UPDATE_FILTER";
export const DELETE_MOVIE = "DELETE_MOVIE"
export const DELETE_LAST_MOVIE = "DELETE_LAST_MOVIE"
export const SET_PAGE = "SET_PAGE"
export const UPDATE_LIKE = "UPDATE_LIKE"
export const UPDATE_DISLIKE = "UPDATE_DISLIKE"
export const LOADING_IN_PROGRESS = "LOADING_IN_PROGRESS"
export const LOADING_MOVIES = "LOADING_MOVIES"